UCS 547 - Accelerated_Data_Science
Assignment_1
ARNAV_VERMA_(102495007)

In [1]:
import numpy as np

1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [3]:
arr = np.array([1,2,3,6,4,5])

In [4]:
print(arr[::-1])

[5 4 6 3 2 1]


2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [5]:
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[1, 2], [3, 4]])

In [6]:
print(np.array_equal(arr1,arr2))

False


3. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [13]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def frequency(arr):
    values, counts = np.unique(arr, return_counts=True)

    max_count = np.max(counts)

    most_freq_values = values[counts == max_count]

    print("Array:", arr)
    print("Most frequent value(s):", most_freq_values)

    for v in most_freq_values:
        indices = np.where(arr == v)[0]
        print(f"Indices of {v}:", indices)
frequency(x)
frequency(y)


Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent value(s): [1]
Indices of 1: [0 5 7 8 9]
Array: [1 1 1 2 3 4 2 4 3 3]
Most frequent value(s): [1 3]
Indices of 1: [0 1 2]
Indices of 3: [4 8 9]


4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii. Sum of all element’s row-wise
iii. Sum of all element’s column-wise

In [10]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg,axis=1))
print(np.sum(gfg,axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]
